# write a program to store seven fruits in a list elements by the user
fruits=[]

f1=input("enter fruits name:") 
fruits.append(f1)
f2=input("enter fruits name:")
fruits.append(f2)
f3=input("enter fruits name:")
fruits.append(f3)
f4=input("enter fruits name:")
fruits.append(f4)
f5=input("enter fruits name:")
fruits.append(f5)
f6=input("enter fruits name:")
fruits.append(f6)
f7=input("enter fruits name:")
fruits.append(f7)
f8=input("enter fruits name:")
fruits.append(f8)
print(fruits)